version: '3'
name: meow-project  # Changed project name here


volumes:
  app_data:
  vscode-server:
  cache:

services:
  app:
    build: .
    image: meow-app:latest  # Updated image name
    container_name: meow-project  # Changed container name here
    privileged: true
    hostname: meow-project  # Updated hostname
    restart: always
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      - "DISPLAY"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}"
    volumes:
      - .:/app
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.Xauthority:/home/admin/.Xauthority:rw"
      - "/dev/*:/dev/*"
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root"]

  docs:
    image: jekyll/jekyll:latest
    container_name: meow_docs
    volumes:
    - ./docs:/srv/jekyll
    - ./docs/Gemfile:/srv/jekyll/Gemfile
    ports:
      - "4000:4000"
    command: ["jekyll", "serve", "--watch", "--drafts"]

  experiments:
    build:
      context: .
      dockerfile: expts.dockerfile
    entrypoint: "bash"
    tty: true
    volumes:
      - app_data:/app/data
      - vscode-server:/root/.vscode-server
      - cache:/root/.cache/
    environment:
      - "HF_HOME=/app/.cache"
      - "HF_TOKEN=${HF_TOKEN}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
