name: Jekyll Build
on:
  push:
    branches:
      - main
  # pull_request:
  #   type: [opened, reopened, synchronize]

jobs:
  jekyll_build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/docs/Gemfile
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Update RubyGems
      run: gem update --system 3.3.3
    - name: Bundle Install
      run: |
        cd docs
        bundle install
    - name: Build Jekyll site
      run: bundle exec jekyll build -s docs -d _site --config docs/_config_local.yml
